'use client'
import { useState } from 'react'
type Web3Panel = 'token' | 'audit' | 'wallet' | 'rank' | 'meme' | 'alpha'
const CHAINS = [{id:'56',name:'BSC'},{id:'1',name:'ETH'},{id:'8453',name:'Base'},{id:'CT_501',name:'Solana'},{id:'137',name:'Polygon'}]
const CHAIN_PARAM: Record<string,string> = {'56':'bsc','1':'eth','8453':'base','CT_501':'solana','137':'polygon'}
const RANK_TYPES = [{id:'trending',label:'🔥 Trending'},{id:'top-searched',label:'🔍 Top Searched'},{id:'alpha',label:'⭐ Alpha'},{id:'smart-money',label:'🐋 Smart Money'},{id:'meme',label:'🐸 Meme'},{id:'social',label:'📣 Social'}]
const MEME_STAGES = [{id:'new',label:'🆕 New'},{id:'finalizing',label:'⏳ Finalizing'},{id:'migrated',label:'✅ Migrated'}]
const PANELS = [{id:'token',label:'Token Lookup',icon:'🔎'},{id:'audit',label:'Contract Audit',icon:'🛡'},{id:'wallet',label:'Wallet Tracker',icon:'👛'},{id:'rank',label:'Rankings',icon:'📊'},{id:'meme',label:'Meme Rush',icon:'🚀'},{id:'alpha',label:'Alpha',icon:'⭐'}]

function fmtNum(n:any){const v=parseFloat(n);if(isNaN(v))return'—';if(v>1e9)return'$'+(v/1e9).toFixed(2)+'B';if(v>1e6)return'$'+(v/1e6).toFixed(2)+'M';if(v>1e3)return'$'+(v/1e3).toFixed(2)+'K';if(v>1)return'$'+v.toFixed(4);return'$'+v.toFixed(8)}
async function skillFetch(skill:string,params:Record<string,string>={}){const qs=new URLSearchParams({skill,...params}).toString();const res=await fetch(`/api/skills?${qs}`);return res.json()}
function Panel({title,children}:{title:string;children:React.ReactNode}){return(<div className="rounded-md overflow-hidden" style={{border:'1px solid var(--border)'}}><div className="px-4 py-2.5 border-b" style={{background:'var(--bg3)',borderColor:'var(--border)'}}><span className="mono text-[10px] uppercase tracking-widest" style={{color:'var(--text3)'}}>{title}</span></div><div style={{background:'var(--bg2)'}}>{children}</div></div>)}
function ChainBar({chain,setChain,chains=CHAINS}:{chain:string;setChain:(c:string)=>void;chains?:typeof CHAINS}){return(<div className="flex gap-2 flex-wrap">{chains.map(c=><button key={c.id} onClick={()=>setChain(c.id)} className="mono text-[10px] px-3 py-1 rounded transition-all" style={{background:chain===c.id?'var(--yellow)':'var(--bg3)',color:chain===c.id?'#000':'var(--text2)',border:chain===c.id?'none':'1px solid var(--border)'}}>{c.name}</button>)}</div>)}
function SearchBar({value,onChange,placeholder,onSearch,loading}:{value:string;onChange:(v:string)=>void;placeholder:string;onSearch:()=>void;loading:boolean}){return(<div className="flex gap-2"><input value={value} onChange={e=>onChange(e.target.value)} onKeyDown={e=>e.key==='Enter'&&onSearch()} placeholder={placeholder} className="flex-1 mono text-sm px-3 py-2.5 rounded-md outline-none" style={{background:'var(--bg3)',border:'1px solid var(--border2)',color:'var(--text)'}} onFocus={e=>(e.target.style.borderColor='var(--yellow)')} onBlur={e=>(e.target.style.borderColor='var(--border2)')}/><button onClick={onSearch} disabled={!value.trim()||loading} className="px-4 py-2 rounded-md text-xs font-bold flex items-center gap-2 transition-all" style={{background:value.trim()?'var(--yellow)':'var(--bg4)',color:value.trim()?'#000':'var(--text3)',cursor:!value.trim()||loading?'not-allowed':'pointer'}}>{loading&&<span className="w-3 h-3 rounded-full border-2 border-black/30 border-t-black animate-spin-slow"/>}{loading?'...':'Search'}</button></div>)}
function Err({msg}:{msg:string}){return<div className="mono text-xs p-2 rounded" style={{background:'rgba(246,70,93,0.08)',color:'var(--red)'}}>{msg}</div>}
function Empty({icon,text}:{icon:string;text:string}){return<div className="py-8 text-center flex flex-col items-center gap-2"><div style={{width:28,height:28,borderRadius:6,border:"1px solid rgba(240,185,11,.2)",opacity:.5,margin:"0 auto",display:"flex",alignItems:"center",justifyContent:"center"}}><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="rgba(240,185,11,.7)" strokeWidth="1.8" strokeLinecap="round"><path d="M9 3H5a2 2 0 0 0-2 2v4m6-6h10a2 2 0 0 1 2 2v4M9 3v18m0 0h10a2 2 0 0 0 2-2v-4M9 21H5a2 2 0 0 1-2-2v-4m0 0h18"/></svg></div><div className="mono text-xs" style={{color:'var(--text3)'}}>{text}</div></div>}
function Spinner(){return<div className="flex justify-center py-6"><span className="w-6 h-6 rounded-full border-2 animate-spin-slow" style={{borderColor:'var(--border2)',borderTopColor:'var(--yellow)'}}/></div>}

function TokenPanel(){
  const [q,setQ]=useState('');const [chain,setChain]=useState('56');const [loading,setL]=useState(false);const [results,setR]=useState<any[]>([]);const [error,setE]=useState('')
  async function search(){setL(true);setE('');setR([]);try{const d=await skillFetch('token-search',{keyword:q,chain:CHAIN_PARAM[chain]});if(d.success){const t=d.data?.data??d.data?.list??d.data??[];setR(Array.isArray(t)?t.slice(0,10):[])}else setE(d.error)}catch(e:any){setE(e.message)}setL(false)}
  return<Panel title="Token Search"><div className="p-4 flex flex-col gap-3"><ChainBar chain={chain} setChain={setChain}/><SearchBar value={q} onChange={setQ} placeholder="Name, symbol, or contract (0x...)" onSearch={search} loading={loading}/>{error&&<Err msg={error}/>}{results.map((t:any,i:number)=><div key={i} className="flex items-center gap-3 p-3 rounded-md" style={{background:'var(--bg3)',border:'1px solid var(--border)'}}>{t.icon&&<img src={t.icon.startsWith('/')?`https://web3.binance.com${t.icon}`:t.icon} alt="" className="w-8 h-8 rounded-full" onError={e=>(e.currentTarget.style.display='none')}/>}<div className="flex-1 min-w-0"><div className="flex items-center gap-2"><span className="font-bold text-sm" style={{color:'var(--text)'}}>{t.symbol??t.name}</span><span className="mono text-[9px] px-1.5 py-0.5 rounded" style={{background:'var(--bg4)',color:'var(--text3)'}}>{t.chainName??''}</span></div><div className="mono text-[10px] truncate" style={{color:'var(--text3)'}}>{t.contractAddress??''}</div></div><div className="text-right shrink-0"><div className="mono text-xs font-bold" style={{color:'var(--text)'}}>{fmtNum(t.price??t.priceUsd)}</div>{t.priceChange24h!=null&&<div className="mono text-[10px]" style={{color:parseFloat(t.priceChange24h)>=0?'var(--green)':'var(--red)'}}>{parseFloat(t.priceChange24h)>=0?'+':''}{parseFloat(t.priceChange24h).toFixed(2)}%</div>}</div></div>)}{!loading&&!results.length&&!error&&<Empty icon="◈" text="Search any Web3 token across BSC, ETH, Base, Solana"/>}</div></Panel>
}

function AuditPanel(){
  const [contract,setC]=useState('');const [chain,setChain]=useState('56');const [loading,setL]=useState(false);const [result,setR]=useState<any>(null);const [error,setE]=useState('')
  async function audit(){setL(true);setE('');setR(null);try{const d=await skillFetch('token-audit',{contract,chain:CHAIN_PARAM[chain]});if(d.success)setR(d.data?.data??d.data);else setE(d.error)}catch(e:any){setE(e.message)}setL(false)}
  const riskScore=result?.riskScore??result?.contractRisk?.riskScore
  const checks=[{l:'Honeypot',v:result?.isHoneypot??result?.contractRisk?.isHoneypot,bad:true},{l:'Blacklist',v:result?.hasBlacklist??result?.contractRisk?.hasBlacklist,bad:true},{l:'Can Mint',v:result?.canMint??result?.contractRisk?.canMint,bad:true},{l:'Is Proxy',v:result?.isProxy,bad:false},{l:'Open Source',v:result?.isOpenSource,bad:false},{l:'Renounced',v:result?.isOwnerRenounced,bad:false}].filter(r=>r.v!==undefined&&r.v!==null)
  return<Panel title="Contract Security Audit"><div className="p-4 flex flex-col gap-3"><ChainBar chain={chain} setChain={setChain} chains={CHAINS.slice(0,4)}/><SearchBar value={contract} onChange={setC} placeholder="Contract address (0x...)" onSearch={audit} loading={loading}/>{error&&<Err msg={error}/>}{result&&<div className="flex flex-col gap-3"><div className="flex items-center justify-between p-3 rounded-md" style={{background:'var(--bg3)',border:'1px solid var(--border)'}}><div><div className="font-bold text-sm" style={{color:'var(--text)'}}>{result.name??result.tokenName??'Token'}</div><div className="mono text-[10px]" style={{color:'var(--text3)'}}>{contract.slice(0,10)}...{contract.slice(-6)}</div></div>{riskScore!=null&&<span className="mono text-[10px] font-bold px-2 py-0.5 rounded" style={{background:parseInt(riskScore)>=70?'rgba(246,70,93,0.12)':parseInt(riskScore)>=40?'rgba(240,185,11,0.12)':'rgba(14,203,129,0.1)',color:parseInt(riskScore)>=70?'var(--red)':parseInt(riskScore)>=40?'var(--yellow)':'var(--green)'}}>{parseInt(riskScore)>=70?'High Risk':parseInt(riskScore)>=40?'Medium':'Safe'} ({riskScore})</span>}</div>{checks.length>0&&<div className="grid grid-cols-2 gap-2">{checks.map(r=><div key={r.l} className="flex items-center justify-between p-2.5 rounded-md" style={{background:'var(--bg3)',border:'1px solid var(--border)'}}><span className="mono text-[10px]" style={{color:'var(--text2)'}}>{r.l}</span><span className="mono text-[10px] font-bold px-2 py-0.5 rounded" style={{background:r.bad?(r.v?'rgba(246,70,93,0.12)':'rgba(14,203,129,0.1)'):(r.v?'rgba(14,203,129,0.1)':'rgba(246,70,93,0.08)'),color:r.bad?(r.v?'var(--red)':'var(--green)'):(r.v?'var(--green)':'var(--red)')}}>{r.v?'YES':'NO'}</span></div>)}</div>}</div>}{!loading&&!result&&!error&&<Empty icon="🛡" text="Paste a contract address to check for honeypots, rug risks, and blacklists"/>}</div></Panel>
}

function WalletPanel(){
  const [address,setA]=useState('');const [chain,setChain]=useState('56');const [loading,setL]=useState(false);const [data,setD]=useState<any>(null);const [error,setE]=useState('')
  async function lookup(){setL(true);setE('');setD(null);try{const d=await skillFetch('address-tokens',{address,chain:CHAIN_PARAM[chain]});if(d.success)setD(d.data?.data??d.data);else setE(d.error)}catch(e:any){setE(e.message)}setL(false)}
  const tokens=data?.list??data?.tokenList??data?.tokens??(Array.isArray(data)?data:[])
  return<Panel title="Wallet Tracker"><div className="p-4 flex flex-col gap-3"><ChainBar chain={chain} setChain={setChain}/><SearchBar value={address} onChange={setA} placeholder="Wallet address (0x... or Solana)" onSearch={lookup} loading={loading}/>{error&&<Err msg={error}/>}{tokens.length>0&&<div className="flex flex-col gap-1.5">{tokens.slice(0,12).map((t:any,i:number)=>{const chg=parseFloat(t.priceChange24h??t.change24h??'0');return(<div key={i} className="grid px-3 py-2 rounded-md items-center" style={{gridTemplateColumns:'1fr 80px 80px 55px',background:'var(--bg3)',border:'1px solid var(--border)'}}><div className="flex items-center gap-2">{t.icon&&<img src={t.icon.startsWith('/')?`https://web3.binance.com${t.icon}`:t.icon} alt="" className="w-5 h-5 rounded-full" onError={e=>(e.currentTarget.style.display='none')}/>}<span className="mono text-xs font-bold truncate" style={{color:'var(--text)'}}>{t.symbol??t.name}</span></div><span className="mono text-[10px]" style={{color:'var(--text2)'}}>{parseFloat(t.balance??t.amount??'0').toFixed(4)}</span><span className="mono text-[10px] font-bold" style={{color:'var(--text)'}}>{fmtNum(t.valueUsd??t.value)}</span><span className="mono text-[10px] font-bold" style={{color:chg>=0?'var(--green)':'var(--red)'}}>{chg>=0?'+':''}{chg.toFixed(1)}%</span></div>)})}</div>}{!loading&&!data&&!error&&<Empty icon="◈" text="Track any wallet — holdings, value, and 24h changes"/>}</div></Panel>
}

function RankPanel(){
  const [type,setType]=useState('trending');const [loading,setL]=useState(false);const [tokens,setT]=useState<any[]>([]);const [error,setE]=useState('')
  async function load(t:string){setType(t);setL(true);setE('');setT([]);try{const d=await skillFetch('market-rank',{type:t});if(d.success){const list=d.data?.data?.list??d.data?.list??d.data?.data??(Array.isArray(d.data)?d.data:[]);setT(Array.isArray(list)?list.slice(0,15):[])}else setE(d.error)}catch(e:any){setE(e.message)}setL(false)}
  return<Panel title="Market Rankings"><div className="p-4 flex flex-col gap-3"><div className="flex gap-2 flex-wrap">{RANK_TYPES.map(rt=><button key={rt.id} onClick={()=>load(rt.id)} className="mono text-[10px] px-3 py-1.5 rounded transition-all" style={{background:type===rt.id?'var(--yellow)':'var(--bg3)',color:type===rt.id?'#000':'var(--text2)',border:type===rt.id?'none':'1px solid var(--border)'}}>{rt.label}</button>)}</div>{error&&<Err msg={error}/>}{loading&&<Spinner/>}{tokens.map((t:any,i:number)=>{const chg=parseFloat(t.priceChange24h??t.change24h??t.changeRate??'0');return(<div key={i} className="flex items-center gap-3 px-3 py-2 rounded-md" style={{background:'var(--bg3)',border:'1px solid var(--border)'}}><span className="mono text-xs font-bold w-5 text-center shrink-0" style={{color:i<3?'var(--yellow)':'var(--text3)'}}>{i+1}</span>{t.icon&&<img src={t.icon.startsWith('/')?`https://web3.binance.com${t.icon}`:t.icon} alt="" className="w-6 h-6 rounded-full shrink-0" onError={e=>(e.currentTarget.style.display='none')}/>}<div className="flex-1 min-w-0"><span className="mono text-xs font-bold" style={{color:'var(--text)'}}>{t.symbol??t.name}</span>{t.chainName&&<span className="mono text-[9px] ml-2 px-1 rounded" style={{background:'var(--bg4)',color:'var(--text3)'}}>{t.chainName}</span>}</div><div className="text-right shrink-0"><div className="mono text-xs font-bold" style={{color:'var(--text)'}}>{fmtNum(t.price??t.priceUsd)}</div>{!isNaN(chg)&&<div className="mono text-[10px]" style={{color:chg>=0?'var(--green)':'var(--red)'}}>{chg>=0?'+':''}{chg.toFixed(2)}%</div>}</div></div>)})}{!loading&&!tokens.length&&!error&&<Empty icon="◈" text="Select a ranking type above"/>}</div></Panel>
}

function MemePanel(){
  const [stage,setStage]=useState('new');const [chain,setChain]=useState('56');const [loading,setL]=useState(false);const [memes,setM]=useState<any[]>([]);const [error,setE]=useState('')
  async function load(s:string,c:string){setStage(s);setChain(c);setL(true);setE('');setM([]);try{const d=await skillFetch('meme-rush',{stage:s,chain:CHAIN_PARAM[c]});if(d.success){const list=d.data?.data?.list??d.data?.list??d.data?.data??(Array.isArray(d.data)?d.data:[]);setM(Array.isArray(list)?list.slice(0,15):[])}else setE(d.error)}catch(e:any){setE(e.message)}setL(false)}
  return<Panel title="Meme Rush — Launchpad"><div className="p-4 flex flex-col gap-3"><div className="flex items-center justify-between gap-2 flex-wrap"><div className="flex gap-2">{MEME_STAGES.map(ms=><button key={ms.id} onClick={()=>load(ms.id,chain)} className="mono text-[10px] px-3 py-1.5 rounded transition-all" style={{background:stage===ms.id?'var(--yellow)':'var(--bg3)',color:stage===ms.id?'#000':'var(--text2)',border:stage===ms.id?'none':'1px solid var(--border)'}}>{ms.label}</button>)}</div><div className="flex gap-2">{[{id:'56',name:'BSC'},{id:'CT_501',name:'Solana'}].map(c=><button key={c.id} onClick={()=>load(stage,c.id)} className="mono text-[10px] px-3 py-1 rounded transition-all" style={{background:chain===c.id?'var(--yellow)':'var(--bg3)',color:chain===c.id?'#000':'var(--text2)',border:chain===c.id?'none':'1px solid var(--border)'}}>{c.name}</button>)}</div></div>{error&&<Err msg={error}/>}{loading&&<Spinner/>}{memes.map((t:any,i:number)=><div key={i} className="flex items-center gap-3 px-3 py-2.5 rounded-md" style={{background:'var(--bg3)',border:'1px solid var(--border)'}}>{t.icon&&<img src={t.icon.startsWith('/')?`https://web3.binance.com${t.icon}`:t.icon} alt="" className="w-7 h-7 rounded-full shrink-0" onError={e=>(e.currentTarget.style.display='none')}/>}<div className="flex-1 min-w-0"><div className="mono text-xs font-bold" style={{color:'var(--text)'}}>{t.symbol??t.name}</div><div className="mono text-[9px] truncate" style={{color:'var(--text3)'}}>{t.contractAddress??t.address??''}</div></div><div className="text-right shrink-0"><div className="mono text-xs" style={{color:'var(--text2)'}}>{fmtNum(t.marketCap??t.mc)}</div><div className="mono text-[9px]" style={{color:'var(--text3)'}}>mcap</div></div></div>)}{!loading&&!memes.length&&!error&&<Empty icon="◈" text="Click a stage to discover meme tokens from launchpads"/>}</div></Panel>
}

function AlphaPanel(){
  const [loading,setL]=useState(false);const [tokens,setT]=useState<any[]>([]);const [error,setE]=useState('')
  async function load(){setL(true);setE('');try{const d=await skillFetch('alpha-tokens');if(d.success){const list=d.data?.data??d.data?.list??(Array.isArray(d.data)?d.data:[]);setT(Array.isArray(list)?list.slice(0,12):[])}else setE(d.error)}catch(e:any){setE(e.message)}setL(false)}
  return<Panel title="Binance Alpha Tokens"><div className="p-4 flex flex-col gap-3"><button onClick={load} disabled={loading} className="flex items-center justify-center gap-2 py-2.5 rounded-md text-sm font-bold" style={{background:'var(--yellow)',color:'#000',cursor:loading?'not-allowed':'pointer',opacity:loading?0.7:1}}>{loading&&<span className="w-4 h-4 rounded-full border-2 border-black/30 border-t-black animate-spin-slow"/>}{loading?'Loading...':'⭐ Load Alpha Tokens'}</button>{error&&<Err msg={error}/>}{tokens.map((t:any,i:number)=><div key={i} className="flex items-center gap-3 p-3 rounded-md" style={{background:'var(--bg3)',border:'1px solid rgba(240,185,11,0.15)'}}>{(t.icon??t.logo??t.iconUrl)&&<img src={t.icon??t.logo??t.iconUrl} alt="" className="w-8 h-8 rounded-full shrink-0" onError={e=>(e.currentTarget.style.display='none')}/>}<div className="flex-1 min-w-0"><div className="font-bold text-sm" style={{color:'var(--text)'}}>{t.symbol??t.tokenSymbol??t.name}</div><div className="mono text-[10px]" style={{color:'var(--text3)'}}>{t.tokenName??t.description??''}</div></div><div className="flex flex-col items-end gap-1">{t.price!=null&&<div className="mono text-xs font-bold" style={{color:'var(--text)'}}>{fmtNum(t.price)}</div>}<span className="mono text-[9px] px-2 py-0.5 rounded" style={{background:'rgba(240,185,11,0.12)',color:'var(--yellow)'}}>Alpha</span></div></div>)}{!loading&&!tokens.length&&!error&&<Empty icon="◈" text="Click to load current Binance Alpha token listings"/>}</div></Panel>
}

export default function Web3Tab(){
  const [active,setActive]=useState<Web3Panel>('token')
  return(
    <div className="flex-1 overflow-y-auto" style={{background:"var(--bg)"}}>
    <div className="max-w-3xl mx-auto px-6 py-6">
      <div className="mb-5">
        <h2 className="text-xl font-extrabold uppercase tracking-tight" style={{color:"var(--text)"}}>Web3 <span style={{color:"var(--yellow)"}}>Intelligence</span></h2>
        <p className="mono text-xs mt-0.5" style={{color:'var(--text3)'}}>Powered by Binance Skills Hub · token data, audits, wallet tracking, rankings</p>
      </div>
      <div className="flex gap-2 mb-5 flex-wrap">
        {PANELS.map(p=><button key={p.id} onClick={()=>setActive(p.id as Web3Panel)} className="flex items-center gap-1.5 px-4 py-2 rounded-md text-sm font-semibold transition-all" style={{background:active===p.id?'var(--yellow)':'var(--bg2)',color:active===p.id?'#000':'var(--text2)',border:active===p.id?'none':'1px solid var(--border)'}}><span>{p.icon}</span>{p.label}</button>)}
      </div>
      {active==='token'&&<TokenPanel/>}
      {active==='audit'&&<AuditPanel/>}
      {active==='wallet'&&<WalletPanel/>}
      {active==='rank'&&<RankPanel/>}
      {active==='meme'&&<MemePanel/>}
      {active==='alpha'&&<AlphaPanel/>}
    </div>
  </div>
  )
}